//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBinhLuan { get; set; }
        public Nullable<int> MaTruyen { get; set; }
        public int MaTK { get; set; }
        public string HovaTen { get; set; }
        public string Avatar { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayBinhLuan { get; set; }
        public Nullable<int> PhanHoi { get; set; }
        public Nullable<int> SoChuong { get; set; }
        public int LoaiHD { get; set; }
    }
}
