//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public Nullable<int> MaTruyen { get; set; }
        public int MaTK { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
        public string DanhGia1 { get; set; }
    }
}
