//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HanhDongCuaTK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HanhDongCuaTK()
        {
            this.HanhDongCuaTK1 = new HashSet<HanhDongCuaTK>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaTruyen { get; set; }
        public Nullable<int> SoChuong { get; set; }
        public int LoaiHD { get; set; }
        public System.DateTime NgayHanhDong { get; set; }
        public int MaTK { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public Nullable<int> TacGia { get; set; }
        public Nullable<int> PhanHoi { get; set; }
        public Nullable<int> MaNhom { get; set; }
    
        public virtual ChuongTruyen ChuongTruyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanhDongCuaTK> HanhDongCuaTK1 { get; set; }
        public virtual HanhDongCuaTK HanhDongCuaTK2 { get; set; }
        public virtual NhomTG NhomTG { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
