//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luotthich
    {
        public int MaTK { get; set; }
        public int MaTruyen { get; set; }
        public System.DateTime Ngaythich { get; set; }
    
        public virtual Truyen Truyen { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
