//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TacGia()
        {
            this.NhomTGs = new HashSet<NhomTG>();
            this.QuanLyHinhAnhs = new HashSet<QuanLyHinhAnh>();
            this.ThanhVienNhoms = new HashSet<ThanhVienNhom>();
            this.TruyenTacGias = new HashSet<TruyenTacGia>();
        }
    
        public int MaTG { get; set; }
        public int MaTK { get; set; }
        public string ButDanh { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public int VaiTro { get; set; }
        public bool DaDuyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomTG> NhomTGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyHinhAnh> QuanLyHinhAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhVienNhom> ThanhVienNhoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruyenTacGia> TruyenTacGias { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
