//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public int MaTG { get; set; }
        public string ButDanh { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public int VaiTro { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
        public Nullable<bool> Khoa { get; set; }
    }
}
