//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheodoTG
    {
        public int MaTK { get; set; }
        public Nullable<int> MaTG { get; set; }
        public System.DateTime Ngaytheodoi { get; set; }
        public int LoaiHD { get; set; }
    }
}
