//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int MaThongBao { get; set; }
        public int MaTK { get; set; }
        public string ThongBao1 { get; set; }
        public System.DateTime NgayThongBao { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public int LoaiHD { get; set; }
        public Nullable<int> MaTruyen { get; set; }
        public Nullable<int> SoChuong { get; set; }
        public Nullable<int> TacGia { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> PhanHoi { get; set; }
    }
}
