//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraoDoiNhom
    {
        public int MaTraoDoi { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public int MaTV { get; set; }
        public string Avatar { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayViet { get; set; }
        public Nullable<int> PhanHoi { get; set; }
        public int LoaiHD { get; set; }
        public string ButDanh { get; set; }
    }
}
