//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruyenTacGia
    {
        public int MaTruyen { get; set; }
        public int MaTG { get; set; }
        public int VaiTro { get; set; }
        public Nullable<int> DangNhom { get; set; }
    
        public virtual NhomTG NhomTG { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
