//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTruyen
    {
        public int MaTruyen { get; set; }
        public string TenTruyen { get; set; }
        public int MaLoai { get; set; }
        public string TacGiaGoc { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public bool TamAn { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
        public Nullable<bool> Khoa { get; set; }
        public int LoaiTruyen { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<int> LuotXem { get; set; }
    }
}
