//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vvTruyen
    {
        public int MaTruyen { get; set; }
        public string TenTruyen { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string AnhBia { get; set; }
        public int MaLoai { get; set; }
        public Nullable<int> SoChuong1 { get; set; }
        public Nullable<int> SoChuong2 { get; set; }
        public Nullable<int> SoChuong3 { get; set; }
        public string TenChuong1 { get; set; }
        public string TenChuong2 { get; set; }
        public string TenChuong3 { get; set; }
        public int LoaiTruyen { get; set; }
    }
}
